name: CI/CD Auto-Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create Config File
        run: |
          echo '{
            "remote_host": "${{ secrets.REMOTE_HOST }}",
            "remote_user": "ubuntu",
            "ssh_key_path": "/home/runner/.ssh/id_rsa",
            "docker_user": "artemprys",
            "project_name": "my-web-app",
            "version": "1.0",
            "external_port": 80
          }' > config.json

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run Deploy Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          SSH_KEY_PATH: /home/runner/.ssh/id_rsa
        run: python deploy.py